### ISSUE TITLE
printing does not work

### ISSUE THREAD

**Issue by carolbooth2** [jsteyn/certify#3]
Setup with one user selected (some fields mismatched)
![image](https://github.com/user-attachments/assets/29f92153-fc16-46c4-95ab-94f2632ac33e)

no additonal windows opened, console output:
`2024-12-16 13:07:56 ERROR LearnerPanel - /home/campus.ncl.ac.uk/ncb176/.certify/991074-attendance.svg (No such file or directory)`

**Comment by carolbooth2** [comment]
Attempted with a correctly formed user line (Carol Booth / A G Student) and got a longer console output:

```
java.io.FileNotFoundException: swc-attendance.svg (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at com.jannetta.certify.controller.Globals.svg2pdf(Globals.java:402)
	at com.jannetta.certify.view.LearnerPanel.lambda$actionPerformed$3(LearnerPanel.java:325)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.jannetta.certify.view.LearnerPanel.actionPerformed(LearnerPanel.java:303)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
    

```

**Comment by carolbooth2** [comment]
Directory contents

```
ncb176@sage-302596 ~/Certify % ls -al
total 9348
drwxr-xr-x  2 ncb176 1999    4096 Dec 16 12:07 .
drwxr-xr-x 36 ncb176 1999    4096 Dec 16 13:19 ..
-rwxr-xr-x  1 ncb176 1999 9560507 Dec 16 12:06 Certify.jar
ncb176@sage-302596 ~/Certify % ls -al ~/.certify 
total 640
drwxr-xr-x  2 ncb176 1999   4096 Dec 16 12:59  .
drwxr-xr-x 36 ncb176 1999   4096 Dec 16 13:19  ..
-rw-r--r--  1 ncb176 1999  66825 Dec 16 13:14  1234.svg
-rw-r--r--  1 ncb176 1999  28229 Dec 16 12:54  CertifyLogo.svg
-rw-r--r--  1 ncb176 1999 144823 Dec 16 12:54  dc-attendance.svg
-rw-r--r--  1 ncb176 1999 120446 Dec 16 12:54  lc-attendance.svg
-rw-r--r--  1 ncb176 1999   6825 Dec 16 13:07  Learners.json
-rw-r--r--  1 ncb176 1999    998 Dec 16 12:54 'Lessons (1).json'
-rw-r--r--  1 ncb176 1999     80 Dec 16 13:02  Lessons.json
-rw-r--r--  1 ncb176 1999 183028 Dec 16 12:54  pad-attendance.svg
-rw-r--r--  1 ncb176 1999  66826 Dec 16 12:54  swc-attendance.svg
-rw-r--r--  1 ncb176 1999    427 Dec 16 13:02  system.properties
-rw-r--r--  1 ncb176 1999    641 Dec 16 13:00  Workshops.json
ncb176@sage-302596 ~/Certify % 


```

**Comment by carolbooth2** [comment]
Misunderstood intended behaviour.  A file was created in the .certify directory
